tmax=200;
dt=0.1;
nsteps=(round(tmax/dt));
u_in=zeros(2,nsteps);
tswitch=1e8;
ttt =tswitch;
u_in(:,round(ttt/dt):end)=epsilonmag*[cos(psi);sin(psi)]*...
                ones(1,size(u_in(:,round(ttt/dt):end),2));

[xx,zz,xx_rec]=fast_conv_to_fp_extended(trained_net{1},[],...
    struct('xinit',x_cl(:,end),...
    'ol',0,...
    'tmax',tmax,...
    'dt',dt,...
    'u_in',u_in,...
    'save_neurons',[1:50:1000]));

rin_vec=0.5:0.05:2;

[xol_rsweep,...
    ]=fast_conv_to_fp(trained_net{1},...
    [cos(psi);sin(psi)]*rin_vec,...
    struct('ol',1));
zol_rsweep=trained_net{1}.wout'*net.phi(xol_rsweep);

%% 
[xol_finalpt,...
    ]=fast_conv_to_fp(trained_net{1},...
    [cos(psi);sin(psi)]*epsilonmag+zzz,...
    struct('ol',1));
zol_finalpt=trained_net{1}.wout'*net.phi(xol_finalpt);
%%
[xol_finalptNrm,...
    ]=fast_conv_to_fp(trained_net{1},...
    [cos(psi);sin(psi)]*epsilonmag+zzz/norm(zzz)*hp.A,...
    struct('ol',1));
zol_finalptNrm=trained_net{1}.wout'*net.phi(xol_finalptNrm);